# Generated by Django 3.0.3 on 2020-06-12 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('prfile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tag', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('prfile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_tag', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Owner_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post_picutre', models.ImageField(null=True, upload_to='')),
                ('shop_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.Shop_Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=128, null=True)),
                ('shop_id', models.CharField(max_length=128, null=True)),
                ('shop_address', models.CharField(max_length=240, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('shop_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.Shop_Owner')),
                ('shop_tag', models.ManyToManyField(to='ecmsapp.Shop_Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'OutDoor')], max_length=128)),
                ('product_tag', models.ManyToManyField(to='ecmsapp.Product_Tag')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.Shop')),
                ('shop_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.Shop_Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post_picutre', models.ImageField(null=True, upload_to='')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.Customer')),
            ],
        ),
    ]
