# Generated by Django 3.0.3 on 2020-06-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
