# Generated by Django 3.0.3 on 2020-06-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0004_notice_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='prfile_pic',
            new_name='profile_pic',
        ),
    ]
