# Generated by Django 3.0.3 on 2020-06-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0005_auto_20200627_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
